export const REQUEST_MOVIE = 'REQUEST_MOVIE'
export const RECEIVE_MOVIE = 'RECEIVE_MOVIE'
export const EDIT_MOVIE = 'EDIT_MOVIE'
export const DELETE_MOVIE = 'DELETE_MOVIE'
export const ADD_MOVIE = 'ADD_MOVIE'